services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345679
      POSTGRES_DB: quizaar_dev  
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

  app:
    build: .
    
    command:     sh -c "/wait-for-it.sh db:5432 -- mix ecto.create &&
             mix ecto.migrate &&
             mix phx.server"
    environment:
   
   
      DATABASE_URL: postgres://postgres:12345679@db:5432/quizaar_dev
     

    depends_on:
      - db
    
    ports:
      - "4000:4000" 
 
    
volumes:
  pgdata: