name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Copy code to server
      run: |
        rsync -az --delete -e "ssh" ./ root@116.203.210.54:/opt/quizaar

    - name: Write .env on server
      run: |
        ssh root@116.203.210.54 "printf '%s\n' '${{ secrets.ENV_PROD }}' > /opt/quizaar/.env"

    - name: Build and run Docker Compose
      run: |
        ssh root@116.203.210.54 "cd /opt/quizaar && docker compose pull && docker compose build && docker compose up -d"
